# Generated by Django 4.2.21 on 2025-07-23 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payments", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentmethod",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="Deletado em"
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="is_deleted",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="Deletado"
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="UUID Público",
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="Deletado em"
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="is_deleted",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="Deletado"
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransactionhistory",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="Deletado em"
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransactionhistory",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransactionhistory",
            name="is_deleted",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="Deletado"
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransactionhistory",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="UUID Público",
            ),
        ),
        migrations.AlterField(
            model_name="userpaymentcard",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="Deletado em"
            ),
        ),
        migrations.AlterField(
            model_name="userpaymentcard",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userpaymentcard",
            name="is_deleted",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="Deletado"
            ),
        ),
        migrations.AlterField(
            model_name="userpaymentcard",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="UUID Público",
            ),
        ),
    ]
