# Generated by Django 4.2.21 on 2025-06-18 03:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_address_options_alter_grouptype_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Nascimento"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("M", "Masculino"),
                    ("F", "Feminino"),
                    ("O", "Outro"),
                    ("P", "Prefiro não informar"),
                ],
                max_length=1,
                verbose_name="Gênero",
            ),
        ),
    ]
