# Generated by Django 4.2.21 on 2025-06-20 12:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_date_of_birth_user_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserLoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("success", models.BooleanField(default=False)),
                ("failure_reason", models.CharField(blank=True, max_length=100)),
                ("requires_verification", models.BooleanField(default=False)),
                ("verification_sent", models.BooleanField(default=False)),
                (
                    "attempted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Tentativa de Login",
                "verbose_name_plural": "Tentativas de Login",
                "indexes": [
                    models.Index(
                        fields=["email", "attempted_at"],
                        name="users_userl_email_596691_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "attempted_at"],
                        name="users_userl_ip_addr_2a04b2_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EmailVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("verification_code", models.CharField(max_length=6)),
                (
                    "verification_type",
                    models.CharField(
                        choices=[
                            ("registration", "Cadastro"),
                            ("password_reset", "Reset de Senha"),
                            ("email_change", "Alteração de Email"),
                            ("login_verification", "Verificação de Login"),
                        ],
                        default="registration",
                        max_length=20,
                    ),
                ),
                ("temp_user_data", models.JSONField(blank=True, default=dict)),
                ("attempts", models.IntegerField(default=0)),
                ("max_attempts", models.IntegerField(default=3)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField()),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("is_used", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Verificação de Email",
                "verbose_name_plural": "Verificações de Email",
                "indexes": [
                    models.Index(
                        fields=["email", "verification_type"],
                        name="users_email_email_a58652_idx",
                    ),
                    models.Index(
                        fields=["verification_code"],
                        name="users_email_verific_fafe8b_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="users_email_expires_083d9c_idx"
                    ),
                ],
            },
        ),
    ]
