# Generated by Django 4.2.21 on 2025-06-20 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_userloginattempt_emailverification"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("L", "Languages"), ("T", "Themes")],
                        max_length=1,
                        verbose_name="Tipo",
                    ),
                ),
                ("value", models.TextField(max_length=2000, verbose_name="Valor")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_pref",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Preferência do Usuário",
                "verbose_name_plural": "Preferências do Usuários",
            },
        ),
    ]
