# Generated by Django 4.2.21 on 2025-06-26 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_userpreferences"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPasswordChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "change_method",
                    models.CharField(
                        choices=[
                            ("self_change", "Alteração pelo usuário"),
                            ("reset_by_email", "Reset por email"),
                            ("admin_change", "Alteração pelo admin"),
                            ("forced_change", "Alteração forçada"),
                        ],
                        default="self_change",
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("changed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Alteração de Senha",
                "verbose_name_plural": "Alterações de Senha",
                "ordering": ["-changed_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "changed_at"],
                        name="users_userp_user_id_4ddbee_idx",
                    ),
                    models.Index(
                        fields=["change_method"], name="users_userp_change__f82ac4_idx"
                    ),
                ],
            },
        ),
    ]
