# Generated by Django 5.2.3 on 2025-06-12 01:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_zipcode_address_postal_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='uuid',
            field=models.UUIDField('UUID Público', default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='grouptype',
            name='uuid',
            field=models.UUIDField('UUID Público', default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField('UUID Público', default=uuid.uuid4, unique=True),
        ),
    ]
