# Generated by Django 5.2.3 on 2025-06-12 01:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_address_uuid_alter_grouptype_uuid_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='address',
            new_name='addresses_user_id_6859f4_idx',
            old_name='address_user_id_871587_idx',
        ),
        migrations.RenameIndex(
            model_name='address',
            new_name='addresses_postal__0e4029_idx',
            old_name='address_postal__ea5372_idx',
        ),
        migrations.RenameIndex(
            model_name='address',
            new_name='addresses_is_defa_a1ccfa_idx',
            old_name='address_is_defa_80f2d6_idx',
        ),
        migrations.AlterField(
            model_name='address',
            name='uuid',
            field=models.UUIDField('UUID Público', default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='grouptype',
            name='uuid',
            field=models.UUIDField('UUID Público', default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField('UUID Público', default=uuid.uuid4, unique=True),
        ),
        migrations.AlterModelTable(
            name='address',
            table='addresses',
        ),
    ]
