# Generated by Django 4.2.21 on 2025-07-23 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_productcategory_options"),
        ("users", "0006_userpasswordchange"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Criado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="UUID Público"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Deletado"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deletado em"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Minha Lista de Desejos",
                        max_length=100,
                        verbose_name="Nome da Lista",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "is_default",
                    models.BooleanField(default=True, verbose_name="Lista Padrão"),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="Lista Pública"),
                ),
                (
                    "is_shared",
                    models.BooleanField(
                        default=False, verbose_name="Lista Compartilhada"
                    ),
                ),
                (
                    "share_token",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        unique=True,
                        verbose_name="Token de Compartilhamento",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shared_with",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_wishlists",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Compartilhada com",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlists",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lista de Desejos",
                "verbose_name_plural": "Listas de Desejos",
            },
        ),
        migrations.CreateModel(
            name="WishlistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Criado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="UUID Público"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Deletado"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deletado em"
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Adicionado em"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Observação")),
                (
                    "priority",
                    models.IntegerField(
                        choices=[
                            (1, "Baixa"),
                            (2, "Média"),
                            (3, "Alta"),
                            (4, "Urgente"),
                        ],
                        default=1,
                        verbose_name="Prioridade",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                        verbose_name="Produto",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.productvariant",
                        verbose_name="Variante",
                    ),
                ),
                (
                    "wishlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="users.wishlist",
                        verbose_name="Lista",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item da Lista de Desejos",
                "verbose_name_plural": "Itens das Listas de Desejos",
                "ordering": ["-priority", "-added_at"],
                "indexes": [
                    models.Index(
                        fields=["wishlist", "added_at"],
                        name="users_wishl_wishlis_a5c082_idx",
                    ),
                    models.Index(
                        fields=["product"], name="users_wishl_product_960bc1_idx"
                    ),
                ],
                "unique_together": {("wishlist", "product", "variant")},
            },
        ),
        migrations.AddIndex(
            model_name="wishlist",
            index=models.Index(
                fields=["user", "is_default"], name="users_wishl_user_id_8bc2d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wishlist",
            index=models.Index(
                fields=["share_token"], name="users_wishl_share_t_2892e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wishlist",
            index=models.Index(
                fields=["is_public"], name="users_wishl_is_publ_b22e94_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="wishlist",
            unique_together={("user", "name")},
        ),
    ]
