# Generated by Django 5.2.3 on 2025-06-12 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_address_user_id_871587_idx_addresses_user_id_6859f4_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='address',
            new_name='address_user_id_871587_idx',
            old_name='addresses_user_id_6859f4_idx',
        ),
        migrations.RenameIndex(
            model_name='address',
            new_name='address_postal__ea5372_idx',
            old_name='addresses_postal__0e4029_idx',
        ),
        migrations.RenameIndex(
            model_name='address',
            new_name='address_is_defa_80f2d6_idx',
            old_name='addresses_is_defa_a1ccfa_idx',
        ),
        migrations.RemoveField(
            model_name='address',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='grouptype',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='uuid',
        ),
        migrations.AlterModelTable(
            name='address',
            table='address',
        ),
    ]
