# Generated by Django 5.2.3 on 2025-06-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
