# Generated by Django 4.2.21 on 2025-06-15 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="herosectionsettings",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hero_section",
                to="core.sitesettings",
            ),
        ),
        migrations.AlterField(
            model_name="herosectionsettings",
            name="title",
            field=models.CharField(max_length=250),
        ),
    ]
