# Generated by Django 4.2.21 on 2025-06-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_herosectionsettings_site_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="herosectionsettings",
            name="sub_title",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="herosectionsettings",
            name="title",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
