# Generated by Django 4.2.21 on 2025-06-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_herosectionsettings_sub_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="corp_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="corp_email_token",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="language",
            field=models.CharField(default="pt-BR", max_length=8),
        ),
    ]
