# Generated by Django 4.2.21 on 2025-06-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_remove_sitesettings_language_languages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="corp_email_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
