# Generated by Django 4.2.21 on 2025-06-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_sitesettings_corp_email_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="site_name",
            field=models.CharField(default="BRV Logistics", max_length=100),
        ),
    ]
