# Generated by Django 4.2.21 on 2025-06-26 00:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_sitesettings_site_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="site_url",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
