# Generated by Django 4.2.21 on 2025-06-15 05:47

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalyticsEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="UUID Público"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Deletado"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deletado em"
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID da Sessão"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("page_view", "Visualização de Página"),
                            ("product_view", "Visualização de Produto"),
                            ("add_to_cart", "Adicionar ao Carrinho"),
                            ("remove_from_cart", "Remover do Carrinho"),
                            ("add_to_wishlist", "Adicionar à Wishlist"),
                            ("purchase", "Compra"),
                            ("search", "Busca"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("registration", "Cadastro"),
                        ],
                        max_length=100,
                        verbose_name="Tipo de Evento",
                    ),
                ),
                (
                    "event_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Dados do Evento"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Endereço IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "referrer",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="Referrer"
                    ),
                ),
                (
                    "page_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="URL da Página"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
            ],
            options={
                "verbose_name": "Evento de Analytics",
                "verbose_name_plural": "Eventos de Analytics",
            },
        ),
        migrations.CreateModel(
            name="CustomerMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Criado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="UUID Público"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Deletado"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deletado em"
                    ),
                ),
                (
                    "total_orders",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total de Pedidos"
                    ),
                ),
                (
                    "total_spent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total Gasto",
                    ),
                ),
                (
                    "average_order_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Valor Médio do Pedido",
                    ),
                ),
                (
                    "last_purchase_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Última Compra"
                    ),
                ),
                (
                    "days_since_last_purchase",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Dias desde a Última Compra"
                    ),
                ),
                (
                    "customer_tier",
                    models.CharField(
                        choices=[
                            ("bronze", "Bronze"),
                            ("silver", "Prata"),
                            ("gold", "Ouro"),
                            ("platinum", "Platina"),
                        ],
                        default="bronze",
                        max_length=20,
                        verbose_name="Categoria do Cliente",
                    ),
                ),
                (
                    "preferred_categories",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Categorias Preferidas"
                    ),
                ),
                (
                    "preferred_payment_method",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Método de Pagamento Preferido",
                    ),
                ),
            ],
            options={
                "verbose_name": "Métricas do Cliente",
                "verbose_name_plural": "Métricas dos Clientes",
            },
        ),
        migrations.CreateModel(
            name="ProductPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Criado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="UUID Público"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Deletado"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deletado em"
                    ),
                ),
                ("date", models.DateField(verbose_name="Data")),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Visualizações"
                    ),
                ),
                (
                    "unique_views_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Visualizações Únicas"
                    ),
                ),
                (
                    "add_to_cart_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Adições ao Carrinho"
                    ),
                ),
                (
                    "purchase_count",
                    models.PositiveIntegerField(default=0, verbose_name="Compras"),
                ),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Receita",
                    ),
                ),
                (
                    "conversion_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Taxa de Conversão",
                    ),
                ),
                (
                    "cart_conversion_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Taxa de Conversão do Carrinho",
                    ),
                ),
                (
                    "average_rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=3,
                        null=True,
                        verbose_name="Avaliação Média",
                    ),
                ),
                (
                    "reviews_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Número de Avaliações"
                    ),
                ),
            ],
            options={
                "verbose_name": "Performance do Produto",
                "verbose_name_plural": "Performance dos Produtos",
            },
        ),
        migrations.CreateModel(
            name="SalesReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="UUID Público"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Deletado"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deletado em"
                    ),
                ),
                ("report_date", models.DateField(verbose_name="Data do Relatório")),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("daily", "Diário"),
                            ("weekly", "Semanal"),
                            ("monthly", "Mensal"),
                            ("yearly", "Anual"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Período",
                    ),
                ),
                (
                    "total_orders",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total de Pedidos"
                    ),
                ),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Receita Total",
                    ),
                ),
                (
                    "total_items_sold",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total de Itens Vendidos"
                    ),
                ),
                (
                    "average_order_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Valor Médio do Pedido",
                    ),
                ),
                (
                    "category_breakdown",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Breakdown por Categoria"
                    ),
                ),
                (
                    "payment_method_breakdown",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Breakdown por Método de Pagamento",
                    ),
                ),
                (
                    "geographic_breakdown",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Breakdown Geográfico"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
            ],
            options={
                "verbose_name": "Relatório de Vendas",
                "verbose_name_plural": "Relatórios de Vendas",
            },
        ),
    ]
