# Generated by Django 4.2.21 on 2025-06-15 05:47

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("marketing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wishlistitem",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="wishlistitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.product",
                verbose_name="Produto",
            ),
        ),
        migrations.AddField(
            model_name="wishlistitem",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.productvariant",
                verbose_name="Variante",
            ),
        ),
        migrations.AddField(
            model_name="wishlistitem",
            name="wishlist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="marketing.wishlist",
                verbose_name="Lista de Desejos",
            ),
        ),
        migrations.AddField(
            model_name="wishlist",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="wishlist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wishlists",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AddField(
            model_name="recentlyviewedproduct",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="recentlyviewedproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.product"
            ),
        ),
        migrations.AddField(
            model_name="recentlyviewedproduct",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="emailcampaign",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customersegment",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="wishlistitem",
            unique_together={("wishlist", "product", "variant")},
        ),
        migrations.AddIndex(
            model_name="recentlyviewedproduct",
            index=models.Index(
                fields=["user", "viewed_at"], name="marketing_r_user_id_f95e1b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recentlyviewedproduct",
            index=models.Index(
                fields=["session_key", "viewed_at"],
                name="marketing_r_session_b4bad0_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="recentlyviewedproduct",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("user__isnull", False),
                    ("session_key__isnull", False),
                    _connector="OR",
                ),
                name="user_or_session_required",
            ),
        ),
        migrations.AddIndex(
            model_name="emailcampaign",
            index=models.Index(fields=["status"], name="marketing_e_status_9e6475_idx"),
        ),
        migrations.AddIndex(
            model_name="emailcampaign",
            index=models.Index(
                fields=["target_audience"], name="marketing_e_target__a287ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailcampaign",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["segment_filters"], name="marketing_e_segment_fd87ca_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="customersegment",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["filters"], name="marketing_c_filters_0ef1f6_gin"
            ),
        ),
    ]
