# Generated by Django 4.2.21 on 2025-07-23 03:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("marketing", "0003_newslettersubscription"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="wishlistitem",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="wishlistitem",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="wishlistitem",
            name="product",
        ),
        migrations.RemoveField(
            model_name="wishlistitem",
            name="variant",
        ),
        migrations.RemoveField(
            model_name="wishlistitem",
            name="wishlist",
        ),
        migrations.DeleteModel(
            name="Wishlist",
        ),
        migrations.DeleteModel(
            name="WishlistItem",
        ),
    ]
