# Generated by Django 4.2.21 on 2025-06-15 05:47

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="UUID Público"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Deletado"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deletado em"
                    ),
                ),
                (
                    "quantity_available",
                    models.IntegerField(
                        default=0, verbose_name="Quantidade Disponível"
                    ),
                ),
                (
                    "quantity_reserved",
                    models.IntegerField(default=0, verbose_name="Quantidade Reservada"),
                ),
                (
                    "quantity_on_order",
                    models.IntegerField(default=0, verbose_name="Quantidade em Pedido"),
                ),
                (
                    "reorder_point",
                    models.IntegerField(default=0, verbose_name="Ponto de Reposição"),
                ),
                (
                    "reorder_quantity",
                    models.IntegerField(
                        default=0, verbose_name="Quantidade de Reposição"
                    ),
                ),
                (
                    "max_stock_level",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Nível Máximo de Estoque"
                    ),
                ),
                (
                    "bin_location",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Localização"
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Custo Unitário",
                    ),
                ),
                (
                    "last_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Último Custo",
                    ),
                ),
                (
                    "average_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Custo Médio",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Item de Estoque",
                "verbose_name_plural": "Itens de Estoque",
                "ordering": ["warehouse", "product"],
            },
        ),
        migrations.CreateModel(
            name="InventoryMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="UUID Público"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Deletado"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deletado em"
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("purchase", "Compra"),
                            ("sale", "Venda"),
                            ("return", "Devolução"),
                            ("adjustment", "Ajuste"),
                            ("transfer_in", "Transferência Entrada"),
                            ("transfer_out", "Transferência Saída"),
                            ("damage", "Dano"),
                            ("expired", "Expirado"),
                            ("promotional", "Promocional"),
                            ("reserved", "Reservado"),
                            ("released", "Liberado"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Movimentação",
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Tipo de Referência"
                    ),
                ),
                (
                    "reference_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID de Referência"
                    ),
                ),
                (
                    "quantity_before",
                    models.IntegerField(verbose_name="Quantidade Anterior"),
                ),
                (
                    "quantity_change",
                    models.IntegerField(verbose_name="Alteração de Quantidade"),
                ),
                (
                    "quantity_after",
                    models.IntegerField(verbose_name="Quantidade Posterior"),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Custo Unitário",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
            ],
            options={
                "verbose_name": "Movimentação de Estoque",
                "verbose_name_plural": "Movimentações de Estoque",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InventoryTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="UUID Público"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Deletado"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deletado em"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("in_transit", "Em Trânsito"),
                            ("completed", "Concluído"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "shipped_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Enviado em"
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Recebido em"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Transferência de Estoque",
                "verbose_name_plural": "Transferências de Estoque",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InventoryTransferItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Criado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="UUID Público"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Deletado"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deletado em"
                    ),
                ),
                (
                    "quantity_requested",
                    models.IntegerField(verbose_name="Quantidade Solicitada"),
                ),
                (
                    "quantity_shipped",
                    models.IntegerField(default=0, verbose_name="Quantidade Enviada"),
                ),
                (
                    "quantity_received",
                    models.IntegerField(default=0, verbose_name="Quantidade Recebida"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
            ],
            options={
                "verbose_name": "Item de Transferência",
                "verbose_name_plural": "Itens de Transferência",
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="UUID Público"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Deletado"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deletado em"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nome")),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Código"),
                ),
                (
                    "address_line_1",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Endereço"
                    ),
                ),
                (
                    "address_line_2",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Complemento"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Cidade"),
                ),
                (
                    "state",
                    models.CharField(blank=True, max_length=100, verbose_name="Estado"),
                ),
                (
                    "postal_code",
                    models.CharField(blank=True, max_length=20, verbose_name="CEP"),
                ),
                (
                    "country",
                    models.CharField(blank=True, max_length=100, verbose_name="País"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                (
                    "manager_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nome do Gerente"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Padrão"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Depósito",
                "verbose_name_plural": "Depósitos",
                "ordering": ["name"],
            },
        ),
    ]
