# Generated by Django 4.2.21 on 2025-06-15 05:47

from django.db import migrations, models
import django.utils.timezone
from models.validators import validate_positive_price
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Criado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="UUID Público"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Deletado"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deletado em"
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Código de Rastreamento",
                    ),
                ),
                (
                    "carrier_reference",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Referência da Transportadora",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("ready_to_ship", "Pronto para Envio"),
                            ("shipped", "Enviado"),
                            ("in_transit", "Em Trânsito"),
                            ("out_for_delivery", "Saiu para Entrega"),
                            ("delivered", "Entregue"),
                            ("failed_delivery", "Falha na Entrega"),
                            ("returned", "Devolvido"),
                        ],
                        default="pending",
                        max_length=50,
                        verbose_name="Status",
                    ),
                ),
                (
                    "shipping_address",
                    models.JSONField(verbose_name="Endereço de Entrega"),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=8,
                        null=True,
                        verbose_name="Peso",
                    ),
                ),
                (
                    "length",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Comprimento",
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Largura",
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Altura",
                    ),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Custo do Envio",
                    ),
                ),
                (
                    "insurance_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Custo do Seguro",
                    ),
                ),
                (
                    "shipped_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Enviado em"
                    ),
                ),
                (
                    "estimated_delivery",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Entrega Estimada"
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Entregue em"
                    ),
                ),
                (
                    "tracking_events",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Eventos de Rastreamento"
                    ),
                ),
            ],
            options={
                "verbose_name": "Envio",
                "verbose_name_plural": "Envios",
            },
        ),
        migrations.CreateModel(
            name="ShipmentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="UUID Público"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Deletado"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deletado em"
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="Quantidade")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
            ],
            options={
                "verbose_name": "Item do Envio",
                "verbose_name_plural": "Itens dos Envios",
            },
        ),
        migrations.CreateModel(
            name="ShippingMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Criado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="UUID Público"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Deletado"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deletado em"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nome")),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Código"),
                ),
                (
                    "carrier",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Transportadora"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Ordem"),
                ),
                (
                    "calculation_method",
                    models.CharField(
                        choices=[
                            ("fixed", "Preço Fixo"),
                            ("weight_based", "Baseado no Peso"),
                            ("zone_based", "Baseado na Zona"),
                            ("api_based", "API da Transportadora"),
                        ],
                        default="fixed",
                        max_length=50,
                        verbose_name="Método de Cálculo",
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Preço Base",
                    ),
                ),
                (
                    "price_per_kg",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Preço por Kg",
                    ),
                ),
                (
                    "free_shipping_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Frete Grátis a partir de",
                    ),
                ),
                (
                    "min_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=8,
                        null=True,
                        verbose_name="Peso Mínimo",
                    ),
                ),
                (
                    "max_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=8,
                        null=True,
                        verbose_name="Peso Máximo",
                    ),
                ),
                (
                    "min_delivery_days",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Dias Mínimos para Entrega"
                    ),
                ),
                (
                    "max_delivery_days",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Dias Máximos para Entrega"
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Configurações"
                    ),
                ),
            ],
            options={
                "verbose_name": "Método de Envio",
                "verbose_name_plural": "Métodos de Envio",
            },
        ),
        migrations.CreateModel(
            name="ShippingZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Criado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="UUID Público"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Deletado"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deletado em"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nome")),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativa")),
            ],
            options={
                "verbose_name": "Zona de Envio",
                "verbose_name_plural": "Zonas de Envio",
            },
        ),
        migrations.CreateModel(
            name="ShippingZoneRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Criado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="UUID Público"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Deletado"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deletado em"
                    ),
                ),
                (
                    "min_weight",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=8,
                        verbose_name="Peso Mínimo",
                    ),
                ),
                (
                    "max_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=8,
                        null=True,
                        verbose_name="Peso Máximo",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[validate_positive_price],
                        verbose_name="Preço",
                    ),
                ),
                (
                    "additional_kg_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Preço por Kg Adicional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Taxa da Zona",
                "verbose_name_plural": "Taxas das Zonas",
            },
        ),
        migrations.CreateModel(
            name="ShippingZoneRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="UUID Público"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Deletado"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deletado em"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("state", "Estado"),
                            ("postal_code", "Faixa de CEP"),
                            ("city", "Cidade"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("value", models.CharField(max_length=100, verbose_name="Valor")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
            ],
            options={
                "verbose_name": "Região da Zona",
                "verbose_name_plural": "Regiões das Zonas",
            },
        ),
    ]
