# Generated by Django 4.2.21 on 2025-06-15 05:47

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0002_initial"),
        ("shipping", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingzoneregion",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="shippingzoneregion",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="regions",
                to="shipping.shippingzone",
            ),
        ),
        migrations.AddField(
            model_name="shippingzonerate",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="shippingzonerate",
            name="method",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="zone_rates",
                to="shipping.shippingmethod",
            ),
        ),
        migrations.AddField(
            model_name="shippingzonerate",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rates",
                to="shipping.shippingzone",
            ),
        ),
        migrations.AddField(
            model_name="shippingzone",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="shippingmethod",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="shipmentitem",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="shipmentitem",
            name="order_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="orders.orderitem"
            ),
        ),
        migrations.AddField(
            model_name="shipmentitem",
            name="shipment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="shipping.shipment",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipments",
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="shipping_method",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shipping.shippingmethod",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.warehouse",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="shippingzoneregion",
            unique_together={("zone", "type", "value")},
        ),
        migrations.AlterUniqueTogether(
            name="shippingzonerate",
            unique_together={("zone", "method", "min_weight")},
        ),
        migrations.AddIndex(
            model_name="shippingmethod",
            index=models.Index(
                fields=["is_active", "sort_order"],
                name="shipping_sh_is_acti_94968a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="shippingmethod",
            index=models.Index(
                fields=["carrier"], name="shipping_sh_carrier_e2981a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shippingmethod",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["configuration"], name="shipping_sh_configu_450ce5_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["tracking_number"], name="shipping_sh_trackin_af3d4f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(fields=["status"], name="shipping_sh_status_0644c6_idx"),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["shipped_at"], name="shipping_sh_shipped_0d4cdb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["shipping_address"], name="shipping_sh_shippin_67a201_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["tracking_events"], name="shipping_sh_trackin_fd0aef_gin"
            ),
        ),
    ]
