# Generated by Django 5.2.2 on 2025-06-07 17:37

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('primary_color', colorfield.fields.ColorField(default='#007bff', image_field=None, max_length=25, samples=None)),
                ('secondary_color', colorfield.fields.ColorField(default='#6c757d', image_field=None, max_length=25, samples=None)),
                ('accent_color', colorfield.fields.ColorField(default='#fd7e14', image_field=None, max_length=25, samples=None)),
                ('text_color', colorfield.fields.ColorField(default='#212529', image_field=None, max_length=25, samples=None)),
                ('heading_color', colorfield.fields.ColorField(default='#212529', image_field=None, max_length=25, samples=None)),
                ('link_color', colorfield.fields.ColorField(default='#007bff', image_field=None, max_length=25, samples=None)),
                ('background_color', colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None)),
                ('footer_background_color', colorfield.fields.ColorField(default='#f8f9fa', image_field=None, max_length=25, samples=None)),
                ('heading_font', models.CharField(default='Roboto', max_length=100)),
                ('body_font', models.CharField(default='Roboto', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='themes/logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='themes/favicons/')),
                ('custom_css', models.TextField(blank=True, null=True)),
                ('show_featured_products', models.BooleanField(default=True)),
                ('show_categories_menu', models.BooleanField(default=True)),
                ('products_per_page', models.PositiveIntegerField(default=12)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
