# Generated by Django 4.2.21 on 2025-06-15 05:47

import colorfield.fields
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Criado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="UUID Público"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Deletado"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deletado em"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=False)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "off_white",
                    colorfield.fields.ColorField(
                        default="#fafafa", image_field=None, max_length=25, samples=None
                    ),
                ),
                (
                    "white",
                    colorfield.fields.ColorField(
                        default="#fcfcfc", image_field=None, max_length=25, samples=None
                    ),
                ),
                (
                    "black",
                    colorfield.fields.ColorField(
                        default="#1b1b1b", image_field=None, max_length=25, samples=None
                    ),
                ),
                (
                    "primary_color",
                    colorfield.fields.ColorField(
                        default="#007bff", image_field=None, max_length=25, samples=None
                    ),
                ),
                (
                    "secondary_color",
                    colorfield.fields.ColorField(
                        default="#6c757d", image_field=None, max_length=25, samples=None
                    ),
                ),
                (
                    "fb_info_color",
                    colorfield.fields.ColorField(
                        default="#336899", image_field=None, max_length=25, samples=None
                    ),
                ),
                (
                    "fb_danger_color",
                    colorfield.fields.ColorField(
                        default="#994233", image_field=None, max_length=25, samples=None
                    ),
                ),
                (
                    "fb_warning_color",
                    colorfield.fields.ColorField(
                        default="#ccbb00", image_field=None, max_length=25, samples=None
                    ),
                ),
                (
                    "fb_success_color",
                    colorfield.fields.ColorField(
                        default="#339938", image_field=None, max_length=25, samples=None
                    ),
                ),
                (
                    "neutral_color",
                    colorfield.fields.ColorField(
                        default="#7c7c7c", image_field=None, max_length=25, samples=None
                    ),
                ),
                (
                    "shadow_color",
                    colorfield.fields.ColorField(
                        default="#0000001a",
                        image_field=None,
                        max_length=25,
                        samples=None,
                    ),
                ),
                ("heading_font", models.CharField(default="Roboto", max_length=100)),
                ("body_font", models.CharField(default="Roboto", max_length=100)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="themes/logos/"),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True, null=True, upload_to="themes/favicons/"
                    ),
                ),
                ("custom_css", models.TextField(blank=True, null=True)),
                ("custom_js", models.TextField(blank=True, null=True)),
                ("show_featured_products", models.BooleanField(default=True)),
                ("show_categories_menu", models.BooleanField(default=True)),
                ("products_per_page", models.PositiveIntegerField(default=10)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
