# Generated by Django 5.2.3 on 2025-06-10 18:13

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='accent_color',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='footer_background_color',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='heading_color',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='link_color',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='text_color',
        ),
        migrations.AddField(
            model_name='theme',
            name='black',
            field=colorfield.fields.ColorField(default='#1b1b1b', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='theme',
            name='custom_js',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='fb_danger_color',
            field=colorfield.fields.ColorField(default='#994233', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='theme',
            name='fb_info_color',
            field=colorfield.fields.ColorField(default='#336899', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='theme',
            name='fb_success_color',
            field=colorfield.fields.ColorField(default='#339938', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='theme',
            name='fb_warning_color',
            field=colorfield.fields.ColorField(default='#8a9933', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='theme',
            name='neutral_color',
            field=colorfield.fields.ColorField(default='#7c7c7c', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='theme',
            name='off_white',
            field=colorfield.fields.ColorField(default='#fafafa', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='theme',
            name='shadow_color',
            field=colorfield.fields.ColorField(default='#0000001a', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='theme',
            name='white',
            field=colorfield.fields.ColorField(default='#fcfcfc', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='theme',
            name='products_per_page',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
