# Generated by Django 5.2.3 on 2025-06-11 06:14

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0002_remove_theme_accent_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='fb_warning_color',
            field=colorfield.fields.ColorField(default='#ccbb00', image_field=None, max_length=25, samples=None),
        ),
    ]
