# Generated by Django 4.2.21 on 2025-06-15 15:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("theme", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="theme",
            options={"verbose_name": "Tema", "verbose_name_plural": "Temas"},
        ),
    ]
