# Generated by Django 5.2.3 on 2025-06-12 01:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_created_at_category_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, verbose_name='UUID Público'),
        ),
    ]
