# Generated by Django 4.2.21 on 2025-06-18 03:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productcategory",
            options={"verbose_name": "Categoria", "verbose_name_plural": "Categorias"},
        ),
    ]
