# Generated by Django 4.2.21 on 2025-07-23 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0003_alter_productcategory_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="Deletado em"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_deleted",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="Deletado"
            ),
        ),
        migrations.AlterField(
            model_name="productattribute",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="Deletado em"
            ),
        ),
        migrations.AlterField(
            model_name="productattribute",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="productattribute",
            name="is_deleted",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="Deletado"
            ),
        ),
        migrations.AlterField(
            model_name="productattribute",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="UUID Público",
            ),
        ),
        migrations.AlterField(
            model_name="productattributevalue",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="Criado em",
            ),
        ),
        migrations.AlterField(
            model_name="productattributevalue",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="Deletado em"
            ),
        ),
        migrations.AlterField(
            model_name="productattributevalue",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="productattributevalue",
            name="is_deleted",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="Deletado"
            ),
        ),
        migrations.AlterField(
            model_name="productattributevalue",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="UUID Público",
            ),
        ),
        migrations.AlterField(
            model_name="productbrand",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="Deletado em"
            ),
        ),
        migrations.AlterField(
            model_name="productbrand",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="productbrand",
            name="is_deleted",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="Deletado"
            ),
        ),
        migrations.AlterField(
            model_name="productbrand",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="UUID Público",
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="Deletado em"
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="is_deleted",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="Deletado"
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="UUID Público",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="Deletado em"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="is_deleted",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="Deletado"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="UUID Público",
            ),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="Deletado em"
            ),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="is_deleted",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="Deletado"
            ),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="UUID Público",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="Deletado em"
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="is_deleted",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="Deletado"
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="UUID Público",
            ),
        ),
    ]
