# Generated by Django 5.2.3 on 2025-06-12 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='uuid',
        ),
    ]
