# Generated by Django 5.2.3 on 2025-06-12 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_category_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
